import { useSession, signOut, signIn } from 'next-auth/react'
import Head from 'next/head'

export default function Home() {
 const { data: session } = useSession()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Turtleshell</h1>
        </div>
        { session ? (      <>
        Signed in as {session.user?.email || 'no email'} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </> ) : (     <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>)}
    
      </main>
    </>
  )
}
