name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Save dependencies
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: node_modules
  
  parallel-jobs:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Components testing
            command: npm run test:components
          - name: Server unit testing
            command: npm run test:unit:server
          - name: Build
            command: npm run build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download dependencies
      uses: actions/download-artifact@v2
      with:
        name: dependencies

    - name: Run ${{ matrix.name }}
      run: ${{ matrix.command }}